openapi: 3.0.3
info:
  title: Opportunity Quote PDF Generator API
  description: |
    A Heroku AppLink microservice that generates PDF quotes from Salesforce Opportunity data.
    This API is designed to be invoked from Salesforce via Heroku AppLink integration.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://xyz.herokuapp.com
    description: Heroku Production Server

paths:
  /generate-quote-pdf:
    post:
      operationId: generateQuotePdf
      summary: Generate PDF Quote for an Opportunity
      description: |
        Generates a PDF quote document for the specified Salesforce Opportunity.
        The PDF is created from the Opportunity details and associated Quote Line Items,
        then uploaded back to Salesforce and linked to the Opportunity record.
      tags:
        - Quote Generation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateQuotePdfRequest"
            examples:
              standard:
                summary: Standard Request
                value:
                  opportunityId: "006XXXXXXXXXXXXXXX"
      x-sfdc:
        heroku:
          authorization:
            connectedApp: "HerokuAppLinkConnector"
      responses:
        "200":
          description: PDF generated and attached successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateQuotePdfResponse"
              examples:
                success:
                  summary: Successful Response
                  value:
                    status: "success"
                    message: "PDF generated and attached to Opportunity."
                    contentDocumentId: "069XXXXXXXXXXXXXXX"
                    contentVersionId: "068XXXXXXXXXXXXXXX"
        "404":
          description: Opportunity not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                notFound:
                  summary: Opportunity Not Found
                  value:
                    status: "error"
                    message: "Opportunity not found"
                    errorCode: "NOT_FOUND"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                serverError:
                  summary: Server Error
                  value:
                    status: "error"
                    message: "Internal Server Error: PDF generation failed"
                    errorCode: "INTERNAL_ERROR"

  /health:
    get:
      operationId: healthCheck
      summary: Health Check Endpoint
      description: Returns the health status of the service
      tags:
        - System
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              examples:
                healthy:
                  summary: Healthy Response
                  value:
                    status: "healthy"
                    version: "1.0.0"
                    timestamp: "2025-12-15T10:30:00Z"

components:
  schemas:
    GenerateQuotePdfRequest:
      type: object
      required:
        - opportunityId
      properties:
        opportunityId:
          type: string
          description: The Salesforce Opportunity ID (18-character ID)
          example: "006XXXXXXXXXXXXXXX"

    GenerateQuotePdfResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          description: Status of the operation
          enum:
            - success
            - error
        message:
          type: string
          description: Human-readable message describing the result
        contentDocumentId:
          type: string
          description: Salesforce ContentDocument ID of the uploaded PDF
          example: "069XXXXXXXXXXXXXXX"
        contentVersionId:
          type: string
          description: Salesforce ContentVersion ID of the uploaded PDF
          example: "068XXXXXXXXXXXXXXX"

    ErrorResponse:
      type: object
      required:
        - status
        - message
        - errorCode
      properties:
        status:
          type: string
          enum:
            - error
        message:
          type: string
          description: Human-readable error message
        errorCode:
          type: string
          description: Machine-readable error code
          enum:
            - NOT_FOUND
            - INTERNAL_ERROR

    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - healthy
            - unhealthy
        version:
          type: string
          description: API version
        timestamp:
          type: string
          format: date-time
          description: Current server timestamp

  securitySchemes:
    AppLinkAuth:
      type: apiKey
      in: header
      name: X-AppLink-Token
      description: Authentication is handled by Heroku AppLink service mesh.

security:
  - AppLinkAuth: []

tags:
  - name: Quote Generation
    description: Endpoints for generating PDF quotes
  - name: System
    description: System health and status endpoints
